stages:
  - build
  - test
build:
  before_script:
    - apt-get update -qq
    - apt-get install -y -qq gcc flex make
  script:
    - make
  artifacts:
    paths:
      - jebwc
    expire_in: 8 hour
test:
  needs: ["build"]
  script: ./jebwc < README.md
